### ISSUE TITLE
phpstan.paths is being applied to phpstan.binPath since v3.2.0

### ISSUE THREAD

**Issue by stefanfisk** [SanderRonde/phpstan-vscode#104]
I have a script in `dev/bin/phpstan` that runs `phpstan` inside of a docker container. This together with `phpstan.paths` has worked great up until v3.2.0. Now the path mapping is being applied to `binPath` which results in the bin not being found.

When this happened there was no immediately clear error message. I first noticed the issue after I was confused about why the problems tab was empty even though I had a clear type mismatch in my code.

**Comment by SanderRonde** [comment]
Hmm I'm not too sure what the best course of action is here. I think it is the "right" way to go for it to be pathmapped. I'd assume that `binPath` points to the PHPStan binary itself in most workspaces, in which case path mapping should be enabled. A couple of ways to fix this for your case:
- You can use the `binCommand` setting instead. This describes the command to be used instead of a file, and is meant specifically for docker-like cases.
- You can use the `PHPStan: Launch setup` command to set up and test your configuration specifically for docker. Then you don't need to refer to a custom script anymore and can use it the "native" way. (unless that script contains some special args of course, which you could add to `binCommand` or `args` but I can imagine if you want to keep it in your script).

**Comment by stefanfisk** [comment]
I cleared all of my settings for the extension and then ran `PHPStan: Launch setup` and now it's all working again.
