### ISSUE TITLE
phpstan runs twice if used with a code formatter

### ISSUE THREAD

**Issue by kdevan** [SanderRonde/phpstan-vscode#38]
Just thought I'd see if anyone else runs into this and if anyone can find a solution. Looking at the logs I noticed that phpstan is running twice when used with a code formatter. In my case I also use Laravel Pint for code formatting. It does make sense because on save phpstan runs, then Laravel Pint runs which saves the file again, so phpstan runs again after that.

I found that it's possible to choose the order of code actions using [this feature](https://github.com/gunadhya/vscode-docs/blob/9ba3b64b202229e05491d0af980ac70ca0aa5563/docs/languages/javascript.md#code-actions-on-save):

```json
"editor.codeActionsOnSave": [
  "source.organizeImports",
  "source.fixAll.eslint"
]
```
But this would require adding a custom code action for phpstan I believe. Kind of like [this extension](https://marketplace.visualstudio.com/items?itemName=rohit-gohri.format-code-action) does.

Has anyone else run into this and is there any other solution?

**Comment by SanderRonde** [comment]
Ah this makes sense... I can't really think of a great solution. I could delay the check until a file has "settled" but there's really no telling how long a formatting operation is going to take. On top of that it would require me to no longer use the standard vscode file-change API which would suck.

I think the easiest solution for now indeed is to use `editor.codeActionsOnSave` and to use `phpstan.scanFileForErrors` as the action. It's not as great as the normal way since this does treat it like a force-check but it's probably better than running it twice..

**Comment by SanderRonde** [comment]
Hmm are you sure? It runs just fine for me with `phpstan.enabled` set to false. Only the watcher should be linked to `phpstan.enabled`. What do the logs in the `output` panel say?

**Comment by SanderRonde** [comment]
Sounds like `editor.codeActionsOnSave` isn't properly populated right? Does it contain the `phpstan.scanFileForErrors` command (and the pint one)?
